# Generated by Django 4.0 on 2021-12-11 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Products', '0003_review_reviewer_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='auther',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auther', to='auth.user'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewed', to='auth.user'),
        ),
        migrations.DeleteModel(
            name='Reviewer',
        ),
    ]
